using System.Text;
using TerraGui.Web.Models;

namespace TerraGui.Web.Services;

/// <summary>
/// Generates a valid terraform.tfvars file from variable definitions and user values.
/// </summary>
public class TfVarsGenerator : ITfVarsGenerator
{
    public string Generate(IEnumerable<TerraformVariable> variables, Dictionary<string, string> values)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("# Generated by TerraGui");
        sb.AppendLine($"# Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        foreach (var variable in variables)
        {
            // Check required
            bool hasValue = values.TryGetValue(variable.Name, out string? rawValue) &&
                            !string.IsNullOrWhiteSpace(rawValue);

            if (variable.Required && !hasValue)
                throw new InvalidOperationException($"Required variable '{variable.Name}' has no value.");

            if (!hasValue)
            {
                // Has a default, skip (user didn't override)
                continue;
            }

            // Add description comment
            if (!string.IsNullOrWhiteSpace(variable.Description))
            {
                sb.AppendLine($"# {variable.Description}");
            }

            if (variable.Sensitive)
            {
                sb.AppendLine("# sensitive");
            }

            string line = FormatVariable(variable, rawValue!);
            sb.AppendLine(line);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string FormatVariable(TerraformVariable variable, string rawValue)
    {
        string formattedValue = FormatValue(variable, rawValue);
        return $"{variable.Name} = {formattedValue}";
    }

    private static string FormatValue(TerraformVariable variable, string rawValue)
    {
        string type = variable.Type.Trim().ToLowerInvariant();
        rawValue = rawValue.Trim();

        // If the value already looks like a complete HCL literal (starts with { or [),
        // pass it through as-is (with normalization)
        if (type == "number")
        {
            return rawValue;
        }

        if (type == "bool")
        {
            return rawValue.ToLowerInvariant() == "true" ? "true" : "false";
        }

        if (type == "string" || (variable.Sensitive && type != "number" && type != "bool"))
        {
            // Strip surrounding quotes if already quoted
            if (rawValue.StartsWith('"') && rawValue.EndsWith('"') && rawValue.Length >= 2)
                rawValue = rawValue[1..^1];
            return $"\"{EscapeHclString(rawValue)}\"";
        }

        if (type.StartsWith("list(") || type.StartsWith("set(") || type.StartsWith("tuple("))
        {
            // Expected: JSON-ish array or newline-separated values
            return FormatListValue(rawValue, type);
        }

        if (type.StartsWith("map(") || type.StartsWith("object("))
        {
            return FormatMapValue(rawValue);
        }

        // "any" or unknown — pass through as-is, quoting if it looks like plain text
        if (rawValue.StartsWith('[') || rawValue.StartsWith('{'))
            return rawValue;

        // Looks like a plain string
        if (rawValue.StartsWith('"') && rawValue.EndsWith('"') && rawValue.Length >= 2)
            return rawValue;

        // Try to detect if it's a number or bool
        if (bool.TryParse(rawValue, out _)) return rawValue.ToLowerInvariant();
        if (double.TryParse(rawValue, System.Globalization.NumberStyles.Any,
            System.Globalization.CultureInfo.InvariantCulture, out _)) return rawValue;

        return $"\"{EscapeHclString(rawValue)}\"";
    }

    private static string FormatListValue(string rawValue, string type)
    {
        // rawValue may be:
        //   - Already an HCL array like ["a", "b"]
        //   - Newline-separated items
        //   - Comma-separated items
        if (rawValue.StartsWith('[') && rawValue.EndsWith(']'))
            return rawValue; // pass through

        // Split by newlines or commas
        var items = rawValue.Contains('\n')
            ? rawValue.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            : rawValue.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        bool isNumeric = type.Contains("number");
        bool isBool = type.Contains("bool");

        var formattedItems = items.Select(item =>
        {
            item = item.Trim();
            if (isNumeric) return item;
            if (isBool) return item.ToLowerInvariant();
            // Strip existing quotes then re-quote
            if (item.StartsWith('"') && item.EndsWith('"') && item.Length >= 2)
                return item;
            return $"\"{EscapeHclString(item)}\"";
        });

        return $"[{string.Join(", ", formattedItems)}]";
    }

    private static string FormatMapValue(string rawValue)
    {
        // If already looks like HCL block, pass through
        if (rawValue.StartsWith('{') && rawValue.EndsWith('}'))
            return rawValue;

        // Try to parse key=value or key:value pairs (newline or comma separated)
        var lines = rawValue.Contains('\n')
            ? rawValue.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            : rawValue.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        var pairs = new List<string>();
        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (string.IsNullOrEmpty(trimmed)) continue;

            int eq = trimmed.IndexOf('=');
            int colon = trimmed.IndexOf(':');
            int sep = eq >= 0 ? eq : colon;

            if (sep > 0)
            {
                string k = trimmed[..sep].Trim().Trim('"');
                string v = trimmed[(sep + 1)..].Trim();
                if (v.StartsWith('"') && v.EndsWith('"') && v.Length >= 2)
                    pairs.Add($"  {k} = {v}");
                else
                    pairs.Add($"  {k} = \"{EscapeHclString(v)}\"");
            }
        }

        if (pairs.Count == 0) return "{}";
        return "{\n" + string.Join("\n", pairs) + "\n}";
    }

    private static string EscapeHclString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("${", "\\${");
}
