using TerraGui.Web.Models;
using TerraGui.Web.Services;
using Xunit;

namespace TerraGui.Tests;

public class TfVarsGeneratorTests
{
    private readonly TfVarsGenerator _gen = new();

    private static TerraformVariable Var(string name, string type, string? def = null, bool sensitive = false) =>
        new() { Name = name, Type = type, Default = def, Sensitive = sensitive };

    // ---- Basic types -------------------------------------------

    [Fact]
    public void Generate_StringValue_QuotedInOutput()
    {
        var vars   = new[] { Var("region", "string") };
        var values = new Dictionary<string, string> { ["region"] = "us-east-1" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("region = \"us-east-1\"", output);
    }

    [Fact]
    public void Generate_NumberValue_UnquotedInOutput()
    {
        var vars   = new[] { Var("count", "number") };
        var values = new Dictionary<string, string> { ["count"] = "5" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("count = 5", output);
    }

    [Fact]
    public void Generate_BoolTrue_OutputsTrue()
    {
        var vars   = new[] { Var("enabled", "bool") };
        var values = new Dictionary<string, string> { ["enabled"] = "true" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("enabled = true", output);
    }

    [Fact]
    public void Generate_BoolFalse_OutputsFalse()
    {
        var vars   = new[] { Var("enabled", "bool") };
        var values = new Dictionary<string, string> { ["enabled"] = "false" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("enabled = false", output);
    }

    [Fact]
    public void Generate_ListOfStrings_ProducesHclArray()
    {
        var vars   = new[] { Var("zones", "list(string)") };
        var values = new Dictionary<string, string> { ["zones"] = "[\"a\", \"b\"]" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("zones =", output);
        Assert.Contains("[", output);
    }

    [Fact]
    public void Generate_MapValue_ProducesHclBlock()
    {
        var vars   = new[] { Var("tags", "map(string)") };
        var values = new Dictionary<string, string> { ["tags"] = "{env = \"prod\"}" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("tags =", output);
        Assert.Contains("{", output);
    }

    // ---- Header ------------------------------------------------

    [Fact]
    public void Generate_AlwaysContainsHeader()
    {
        var vars   = new[] { Var("x", "string", "default") };
        var values = new Dictionary<string, string>();
        var output = _gen.Generate(vars, values);
        Assert.Contains("# Generated by TerraGui", output);
    }

    // ---- Required field missing --------------------------------

    [Fact]
    public void Generate_RequiredFieldMissing_ThrowsInvalidOperation()
    {
        var vars   = new[] { Var("db_password", "string") }; // no default → required
        var values = new Dictionary<string, string>();
        Assert.Throws<InvalidOperationException>(() => _gen.Generate(vars, values));
    }

    // ---- Sensitive comment -------------------------------------

    [Fact]
    public void Generate_SensitiveVariable_AddsSensitiveComment()
    {
        var vars   = new[] { Var("api_key", "string", sensitive: true) };
        var values = new Dictionary<string, string> { ["api_key"] = "secret123" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("# sensitive", output);
        Assert.Contains("api_key =", output);
    }

    // ---- Description comment -----------------------------------

    [Fact]
    public void Generate_VariableWithDescription_AddsComment()
    {
        var v = new TerraformVariable { Name = "region", Type = "string", Description = "AWS region" };
        var values = new Dictionary<string, string> { ["region"] = "eu-west-1" };
        var output = _gen.Generate(new[] { v }, values);
        Assert.Contains("# AWS region", output);
    }

    // ---- Variable with default, no value supplied → skipped ----

    [Fact]
    public void Generate_VariableWithDefaultAndNoValue_NotIncluded()
    {
        var v = new TerraformVariable { Name = "region", Type = "string", Default = "\"us-east-1\"" };
        var values = new Dictionary<string, string>(); // user didn't override
        var output = _gen.Generate(new[] { v }, values);
        Assert.DoesNotContain("region =", output);
    }

    // ---- String already quoted ---------------------------------

    [Fact]
    public void Generate_AlreadyQuotedString_NotDoubleQuoted()
    {
        var vars   = new[] { Var("env", "string") };
        var values = new Dictionary<string, string> { ["env"] = "\"production\"" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("env = \"production\"", output);
        Assert.DoesNotContain("\"\"production\"\"", output);
    }

    // ---- Special chars in string value -------------------------

    [Fact]
    public void Generate_StringWithQuoteChar_EscapedInOutput()
    {
        var vars   = new[] { Var("msg", "string") };
        var values = new Dictionary<string, string> { ["msg"] = "say \"hello\"" };
        var output = _gen.Generate(vars, values);
        Assert.Contains("\\\"hello\\\"", output);
    }
}
